# Generated by Django 5.2.17 on 2026-08-14 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(db_index=True, default='medium', max_length=16)),
                ('confidence', models.CharField(db_index=True, default='medium', max_length=16)),
                ('status', models.CharField(db_index=True, default='open', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('wasted_ms', models.FloatField(default=0)),
                ('wasted_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('evidence', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='traces.session')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='traces.span')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='traces.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='findings.finding')),
            ],
        ),
    ]
