# Generated by Django 5.2.17 on 2026-08-14 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('external_span_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('kind', models.CharField(choices=[('turn', 'turn'), ('model', 'model'), ('tool', 'tool'), ('external', 'external'), ('other', 'other')], db_index=True, default='other', max_length=24)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sequence_no', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='traces.span')),
            ],
            options={
                'ordering': ['started_at', 'sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_session_id', models.CharField(db_index=True, max_length=160)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=80)),
                ('model', models.CharField(blank=True, db_index=True, max_length=160)),
                ('agent_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('correlation_confidence', models.CharField(default='low', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCall',
            fields=[
                ('span', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_call', serialize=False, to='traces.span')),
                ('service', models.CharField(db_index=True, default='jotform', max_length=100)),
                ('method', models.CharField(max_length=16)),
                ('url_template', models.CharField(db_index=True, max_length=500)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('request_bytes', models.PositiveBigIntegerField(default=0)),
                ('response_bytes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStep',
            fields=[
                ('span', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='model_step', serialize=False, to='traces.span')),
                ('step_no', models.PositiveIntegerField()),
                ('stop_reason', models.CharField(blank=True, max_length=80)),
                ('input_tokens', models.BigIntegerField(blank=True, null=True)),
                ('cached_tokens', models.BigIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.BigIntegerField(blank=True, null=True)),
                ('output_tokens', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('span', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tool_call', serialize=False, to='traces.span')),
                ('tool_name', models.CharField(db_index=True, max_length=255)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('argument_hash', models.CharField(db_index=True, max_length=64)),
                ('result_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('result_bytes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='span',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='traces.session'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(default='agent_request', max_length=80)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='traces.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='traces.task'),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('sequence_no', models.PositiveIntegerField()),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('input_tokens', models.BigIntegerField(blank=True, null=True)),
                ('output_tokens', models.BigIntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='traces.session')),
            ],
            options={
                'ordering': ['sequence_no'],
            },
        ),
        migrations.AddField(
            model_name='span',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='traces.turn'),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('pricing_version', models.CharField(default='legacy-unknown', max_length=80)),
                ('estimated', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='traces.span')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='traces.turn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('workspace', 'external_session_id', 'provider'), name='unique_external_session'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_no'), name='unique_session_turn_sequence'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['turn', 'started_at'], name='traces_span_turn_id_0f2c07_idx'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['session', 'kind'], name='traces_span_session_04d68a_idx'),
        ),
    ]
