# Generated by Django 5.2.17 on 2026-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_external_session',
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('workspace', 'external_session_id'), name='unique_external_session'),
        ),
    ]
