# Generated by Django 5.2.17 on 2026-08-27 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aitelemetryusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitelemetryusage',
            name='model_name',
            field=models.CharField(default='gemini-3.5-flash-lite', max_length=64),
        ),
        migrations.AlterField(
            model_name='aitelemetryusage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='aitelemetryusage',
            unique_together={('date', 'model_name')},
        ),
    ]
