# Generated by Django 5.2.17 on 2026-08-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('kind', models.CharField(default='auto', max_length=64)),
                ('inode', models.CharField(blank=True, max_length=64)),
                ('last_offset', models.PositiveBigIntegerField(default=0)),
                ('last_hash', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.CharField(default='1.0', max_length=32)),
                ('status', models.CharField(db_index=True, default='new', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('records_ingested', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('path', 'inode'), name='unique_source_path_inode')],
            },
        ),
        migrations.CreateModel(
            name='QuarantinedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_offset', models.PositiveBigIntegerField()),
                ('raw_preview', models.TextField()),
                ('error_type', models.CharField(max_length=120)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_events', to='ingestion.ingestionsource')),
            ],
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_offset', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('schema_version', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('correlation_confidence', models.CharField(default='low', max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingestion.ingestionsource')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='ingestion_r_event_t_80735a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_offset'), name='unique_source_offset')],
            },
        ),
    ]
